CREATE TABLE WEB_PRODUCT(
	ID NUMBER PRIMARY KEY,
	NAME VARCHAR2(100) NOT NULL,
	MAKER VARCHAR2(100) NOT NULL,
	PRICE NUMBER NOT NULL
)

CREATE SEQUENCE WEB_PRODUCT_SEQ;

INSERT INTO WEB_PRODUCT(ID,NAME,MAKER,PRICE) VALUES(WEB_PRODUCT_SEQ.NEXTVAL,'카스','OB',1500);
INSERT INTO WEB_PRODUCT(ID,NAME,MAKER,PRICE) VALUES(WEB_PRODUCT_SEQ.NEXTVAL,'테라','하이트',1400);
INSERT INTO WEB_PRODUCT(ID,NAME,MAKER,PRICE) VALUES(WEB_PRODUCT_SEQ.NEXTVAL,'맥스','OB',1600);

COMMIT

SELECT *
FROM WEB_PRODUCT

SELECT ID,NAME,MAKER,PRICE FROM WEB_PRODUCT ORDER BY ID DESC;